name: 'ECS Deploy'
author: 'Code4Romania'
description: 'Deploy your application to AWS ECS using Terraform'
inputs:
    AWS_ACCESS_KEY:
        description: ''
        required: true
    AWS_SECRET_KEY:
        description: ''
        required: true
    TERRAFORM_WORKSPACE:
        description: ''
        required: false
        default: 'staging'
    APPLICATION_NAME:
        description: ''
        required: true
    APPLICATION_DOCKER_IMAGE:
        description: ''
        required: true
runs:
    using: 'docker'
    # image: 'debian'
    args:
        - 'version'
    image: 'hashicorp/terraform:0.12.20'
